SELECT 
WEB_STREET_NAME as street_name, 
WEB_SUITE_NUMBER as Suite_number, 
WEB_MKT_CLASS as mkt_class,
 WEB_CLASS as class, 
 WEB_MARKET_MANAGER as market_manager,
  WEB_ZIP as zip , 
  WEB_COMPANY_NAME as company_name,
   WEB_COUNTRY as country,
    WEB_COMPANY_ID as company_id,
     WEB_MKT_ID as MKT_ID,
      WEB_MANAGER as manager, 
      WEB_CITY as city, 
      WEB_SITE_SK as city_SK,
       WEB_STATE as state,
        WEB_STREET_NUMBER as street_number,
         WEB_REC_START_DATE as rec_start_date, 
         WEB_TAX_PERCENTAGE as tax_percentage,
          WEB_COUNTY as county, 
          WEB_SITE_ID as site_id, 
          WEB_MKT_DESC as mkt_desc, 
          WEB_GMT_OFFSET as gmt_offset, 
          WEB_STREET_TYPE as street_type, 
          WEB_OPEN_DATE_SK as open_date_sk, 
          WEB_REC_END_DATE as rec_end_date, 
          WEB_NAME as name, 
          WEB_CLOSE_DATE_SK as close_date_sk,
          _AIRBYTE_NORMALIZED_AT
          From {{source('tpcds','web_site')}}