Select 
I_ITEM_DESC as Item_desc, 
I_CONTAINER as Cointainer, 
I_MANUFACT_ID as Manufact_id, 
I_WHOLESALE_COST as Wholesale_cost, 
I_BRAND_ID as Brand_id, 
I_FORMULATION as Formulation, 
I_CURRENT_PRICE as Current_price, 
I_SIZE as Size, 
I_MANUFACT as Manufact, 
I_REC_START_DATE as Rec_start_date,
I_ITEM_SK as item_SK, 
I_MANAGER_ID as Manager_id, 
I_CLASS as Class, 
I_ITEM_ID as Item_id,
I_CLASS_ID as Class_id, 
I_CATEGORY as Category, 
I_CATEGORY_ID as Category_id, 
I_BRAND as Brand, 
I_UNITS as Units,
I_COLOR as Color, 
I_PRODUCT_NAME as Product_name,
I_REC_END_DATE as Rec_end_date,
_AIRBYTE_NORMALIZED_AT as _Airbyte_normalized_at
FROM {{source('tpcds','item')}}