Select C_SALUTATION as Salutation, 
C_PREFERRED_CUST_FLAG as Preferred_cust_flag, 
C_FIRST_SALES_DATE_SK as Sales_data_SK, 
C_FIRST_SALES_DATE_SK as First_sales_date_sk,
C_CUSTOMER_SK as Customer_SK,
C_LOGIN as Login, 
C_CURRENT_CDEMO_SK as Current_Cdemo_SK, 
C_FIRST_NAME as First_name, 
C_CURRENT_HDEMO_SK as Current_Hdemo_SK, 
C_CURRENT_ADDR_SK as Current_addr_SK, 
C_LAST_NAME as Last_name, 
C_CUSTOMER_ID as Customer_id, 
C_LAST_REVIEW_DATE_SK as Last_review_date_SK, 
C_BIRTH_MONTH as Birth_month, 
C_BIRTH_COUNTRY as Birth_country,
 C_BIRTH_YEAR as Birth_year, 
 C_BIRTH_DAY as Birth_day, 
 C_EMAIL_ADDRESS as email_address, 
 C_FIRST_SHIPTO_DATE_SK as First_shipto_date_SK, 
 _AIRBYTE_NORMALIZED_AT as _airbyte_normalied_at
 from {{source('tpcds','customer')}}