Select CS_WAREHOUSE_SK as Warehouse_SK, 
CS_SHIP_DATE_SK as Ship_date_SK, 
CS_EXT_LIST_PRICE as Ext_list_price, 
CS_QUANTITY as Quantity, 
CS_NET_PAID_INC_TAX as Net_paid_inc_tax, 
CS_SOLD_TIME_SK as Sold_time_SK, 
CS_PROMO_SK as Promo_SK, 
CS_LIST_PRICE as List_price, 
CS_EXT_SHIP_COST as Ext_ship_cost, 
CS_NET_PAID as Net_paid, 
CS_SOLD_DATE_SK as Sold_date_SK, 
CS_EXT_DISCOUNT_AMT as EXT_discount_amt, 
CS_SHIP_ADDR_SK as Ship_addr_SK, 
CS_EXT_TAX as Ext_tax, 
CS_CATALOG_PAGE_SK as Catalog_page_SK, 
CS_NET_PROFIT as Net_profit, 
CS_ITEM_SK as Item_sk, 
CS_BILL_CDEMO_SK as Bill_cdemo_SK, 
CS_BILL_HDEMO_SK as Bill_Hdemo_SK, 
CS_NET_PAID_INC_SHIP as Net_paid_inc_ship, 
CS_COUPON_AMT as Coupon_amt, 
CS_NET_PAID_INC_SHIP_TAX as Net_paid_inc_shiP_tax, 
CS_ORDER_NUMBER as Order_Number, 
CS_EXT_WHOLESALE_COST as Ext_wholesale_cost, 
CS_SHIP_MODE_SK as Ship_mode_SK, 
CS_EXT_SALES_PRICE as EXT_sales_prices,
CS_SHIP_CUSTOMER_SK as Ship_Customer_SK, 
CS_BILL_ADDR_SK as Bill_addr_SK,
CS_SHIP_CDEMO_SK as Ship_Cdeme_SK, 
CS_SHIP_HDEMO_SK as Ship_Hdemo_SK, 
CS_WHOLESALE_COST as Wholesale_cost,
CS_SALES_PRICE as Sales_price,
CS_CALL_CENTER_SK as Call_center, 
CS_BILL_CUSTOMER_SK as Bill_customer, 
_AIRBYTE_NORMALIZED_AT as _airbyte_normalied_at
  FROM {{source('tpcds','catalog_sales')}}


  