Select CC_CLASS as Class, 
CC_CITY as City , 
CC_DIVISION_NAME as Division_name, 
CC_MARKET_MANAGER as Market_manager, 
CC_COMPANY as Company, 
CC_MKT_CLASS as MKT_class, 
CC_ZIP as ZIP, 
CC_STREET_NAME as Street_name,  
CC_REC_END_DATE as Rec_end_date, 
CC_CLOSED_DATE_SK as Closed_date_SK, 
CC_DIVISION as Division,
CC_HOURS as Hours, 
CC_OPEN_DATE_SK as Open_date_SK, 
CC_MKT_DESC as Desc, 
CC_STREET_NUMBER as Street_number, 
CC_NAME as Name, 
CC_CALL_CENTER_SK as Call_center_SK, 
CC_TAX_PERCENTAGE as Tax_percentage, 
CC_SQ_FT as SQ_FT, 
CC_COUNTRY as Country, 
CC_CALL_CENTER_ID as Call_center_id, 
CC_COMPANY_NAME as Company_name, 
CC_STATE as State, 
CC_MKT_ID As MKT_ID, 
CC_COUNTY as County, 
CC_MANAGER as Manager, 
CC_EMPLOYEES as Employees, 
CC_REC_START_DATE as Rec_Start_date, 
CC_SUITE_NUMBER as Suite_number, 
CC_STREET_TYPE as Street_type, 
CC_GMT_OFFSET as GMT_offset,
_AIRBYTE_NORMALIZED_AT as Airbyte_normalized_at
FROM {{source('tpcds','call_center')}}